package:
  name: pipdeptree
  version: "0.5.0"

source:
  fn: pipdeptree-0.5.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pipdeptree/pipdeptree-0.5.0.tar.gz
  md5: 387cd7c02e219c11306f1935383dc791
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pipdeptree = pipdeptree:main
    #
    # Would create an entry point called pipdeptree that calls pipdeptree.main()

    - pipdeptree = pipdeptree:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pip >=1.4.1

  run:
    - python
    - pip >=1.4.1

test:
  # Python imports
  # imports:

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - pipdeptree --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/naiquevin/pipdeptree
  license: MIT License
  summary: 'Command line utility to show dependency tree of packages'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
