package:
  name: python-pptx
  version: "0.5.8"

source:
  fn: python-pptx-0.5.8.tar.gz
  url: https://pypi.python.org/packages/source/p/python-pptx/python-pptx-0.5.8.tar.gz
  md5: 6f95929c13fa87c6e898968b2e513e60
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-pptx = python-pptx:main
    #
    # Would create an entry point called python-pptx that calls python-pptx.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - lxml >=3.1.0
    - pillow >=2.6.1
    - xlsxwriter >=0.5.7

  run:
    - python
    - lxml >=3.1.0
    - pillow >=2.6.1
    - xlsxwriter >=0.5.7

test:
  # Python imports
  imports:
    - pptx
    - pptx.chart
    - pptx.compat
    - pptx.dml
    - pptx.enum
    - pptx.opc
    - pptx.oxml
    - pptx.oxml.chart
    - pptx.oxml.dml
    - pptx.oxml.parts
    - pptx.oxml.shapes
    - pptx.parts
    - pptx.shapes
    - pptx.text

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - behave
    - mock
    - pyparsing >=2.0.1
    - pytest
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/scanny/python-pptx
  license: MIT License
  summary: 'Generate and manipulate Open XML PowerPoint (.pptx) files'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
