package:
  name: memory_profiler
  version: "0.39"

source:
  fn: memory_profiler-0.39.tar.gz
  url: https://pypi.python.org/packages/source/m/memory_profiler/memory_profiler-0.39.tar.gz
  md5: 8d06789eaf07ac20487d8baec27b1a29

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: http://pypi.python.org/pypi/memory_profiler
  license: BSD License
  summary: 'A module for monitoring memory usage of a python program'
