package:
  name: regex
  version: "2015.11.09"

source:
  fn: regex-2015.11.09.tar.gz
  url: https://pypi.python.org/packages/source/r/regex/regex-2015.11.09.tar.gz
  md5: d6c4dd309592151fd61e75260674b68e

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports 
  imports:
    - regex

about:
  home: https://code.google.com/p/mrab-regex-hg/
  license: Python Software Foundation License
