package:
  name: pytest
  version: "2.8.2"

source:
  fn: pytest-2.8.2.tar.gz
  url: https://pypi.python.org/packages/source/p/pytest/pytest-2.8.2.tar.gz
  md5: 96e77b3a2fb40e5d99a1cfba38ac7c6d
#  patches:
   # List any patch files here
   # - fix.patch

build:
  #preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pytest = pytest:main
    #
    # Would create an entry point called pytest that calls pytest.main()

    - py.test = pytest:main
    - py.test-3.3 = pytest:main # [py33]
    - py.test-2.6 = pytest:main # [py26]
    - py.test-2.7 = pytest:main # [py27]

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - py
    - colorama # [win]
    - argparse # [py26]

  run:
    - python
    - py
    - argparse # [py26]

test:
  # Python imports
  imports:
    - _pytest.assertion
    - _pytest
    - pytest

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - py.test --help
    - py.test-3.3 --help # [py33]
    - py.test-2.6 --help # [py26]
    - py.test-2.7 --help # [py27]

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pytest.org
  license: MIT License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
